// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.7.1
// source: get_random_number.proto

package generator

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RandomNumbersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number uint32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Max    uint32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *RandomNumbersRequest) Reset() {
	*x = RandomNumbersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_random_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomNumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNumbersRequest) ProtoMessage() {}

func (x *RandomNumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_random_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNumbersRequest.ProtoReflect.Descriptor instead.
func (*RandomNumbersRequest) Descriptor() ([]byte, []int) {
	return file_get_random_number_proto_rawDescGZIP(), []int{0}
}

func (x *RandomNumbersRequest) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *RandomNumbersRequest) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type RandomNumbersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numbers []uint32 `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
}

func (x *RandomNumbersResponse) Reset() {
	*x = RandomNumbersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_random_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomNumbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNumbersResponse) ProtoMessage() {}

func (x *RandomNumbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_random_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNumbersResponse.ProtoReflect.Descriptor instead.
func (*RandomNumbersResponse) Descriptor() ([]byte, []int) {
	return file_get_random_number_proto_rawDescGZIP(), []int{1}
}

func (x *RandomNumbersResponse) GetNumbers() []uint32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

var File_get_random_number_proto protoreflect.FileDescriptor

var file_get_random_number_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x6e, 0x67, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x40, 0x0a, 0x14, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x31, 0x0a, 0x15, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x32, 0x74, 0x0a, 0x15, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x5b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x21, 0x2e, 0x72, 0x6e, 0x67, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72, 0x6e,
	0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_get_random_number_proto_rawDescOnce sync.Once
	file_get_random_number_proto_rawDescData = file_get_random_number_proto_rawDesc
)

func file_get_random_number_proto_rawDescGZIP() []byte {
	file_get_random_number_proto_rawDescOnce.Do(func() {
		file_get_random_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_random_number_proto_rawDescData)
	})
	return file_get_random_number_proto_rawDescData
}

var file_get_random_number_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_random_number_proto_goTypes = []interface{}{
	(*RandomNumbersRequest)(nil),  // 0: rng_service.RandomNumbersRequest
	(*RandomNumbersResponse)(nil), // 1: rng_service.RandomNumbersResponse
}
var file_get_random_number_proto_depIdxs = []int32{
	0, // 0: rng_service.RandomNumberGenerator.GetRandomNumbers:input_type -> rng_service.RandomNumbersRequest
	1, // 1: rng_service.RandomNumberGenerator.GetRandomNumbers:output_type -> rng_service.RandomNumbersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_random_number_proto_init() }
func file_get_random_number_proto_init() {
	if File_get_random_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_get_random_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomNumbersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_random_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomNumbersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_random_number_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_random_number_proto_goTypes,
		DependencyIndexes: file_get_random_number_proto_depIdxs,
		MessageInfos:      file_get_random_number_proto_msgTypes,
	}.Build()
	File_get_random_number_proto = out.File
	file_get_random_number_proto_rawDesc = nil
	file_get_random_number_proto_goTypes = nil
	file_get_random_number_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RandomNumberGeneratorClient is the client API for RandomNumberGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RandomNumberGeneratorClient interface {
	GetRandomNumbers(ctx context.Context, in *RandomNumbersRequest, opts ...grpc.CallOption) (*RandomNumbersResponse, error)
}

type randomNumberGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomNumberGeneratorClient(cc grpc.ClientConnInterface) RandomNumberGeneratorClient {
	return &randomNumberGeneratorClient{cc}
}

func (c *randomNumberGeneratorClient) GetRandomNumbers(ctx context.Context, in *RandomNumbersRequest, opts ...grpc.CallOption) (*RandomNumbersResponse, error) {
	out := new(RandomNumbersResponse)
	err := c.cc.Invoke(ctx, "/rng_service.RandomNumberGenerator/GetRandomNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomNumberGeneratorServer is the server API for RandomNumberGenerator service.
type RandomNumberGeneratorServer interface {
	GetRandomNumbers(context.Context, *RandomNumbersRequest) (*RandomNumbersResponse, error)
}

// UnimplementedRandomNumberGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedRandomNumberGeneratorServer struct {
}

func (*UnimplementedRandomNumberGeneratorServer) GetRandomNumbers(context.Context, *RandomNumbersRequest) (*RandomNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomNumbers not implemented")
}

func RegisterRandomNumberGeneratorServer(s *grpc.Server, srv RandomNumberGeneratorServer) {
	s.RegisterService(&_RandomNumberGenerator_serviceDesc, srv)
}

func _RandomNumberGenerator_GetRandomNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomNumberGeneratorServer).GetRandomNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rng_service.RandomNumberGenerator/GetRandomNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomNumberGeneratorServer).GetRandomNumbers(ctx, req.(*RandomNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RandomNumberGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rng_service.RandomNumberGenerator",
	HandlerType: (*RandomNumberGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomNumbers",
			Handler:    _RandomNumberGenerator_GetRandomNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "get_random_number.proto",
}
